const ActionTypes = {
  FETCH_EVOLUTIONS: "FETCH_EVOLUTIONS",
  FETCH_EVOLUTIONS_ERROR: "FETCH_EVOLUTIONS_ERROR",
  FETCH_SPECIES: "FETCH_SPECIES",
  FETCH_SPECIES_ERROR: "FETCH_SPECIES_ERROR",
  FETCH_POKEMON: "FETCH_POKEMON",
  FETCH_POKEMON_ERROR: "FETCH_POKEMON_ERROR",
  FETCH_POKEMONS: "FETCH_POKEMONS",
  FETCH_POKEMONS_ERROR: "FETCH_POKEMONS_ERROR",
  FILTER_POKEMONS: "FILTER_POKEMONS",
  FETCH_TYPES: "FETCH_TYPES",
  FETCH_TYPES_ERROR: "FETCH_TYPES_ERROR",
  FETCH_MOVE: "FETCH_MOVE",
  CLEAN_MOVE: "CLEAN_MOVE"
};

export default ActionTypes;
